### ISSUE TITLE
Question: state transition diagram

### ISSUE THREAD

**Issue by erikvdvelden** [aws/aws-sdk-android#104]
I noticed the following behaviour; when I first get the onError, then the state change to FAILURE and when I then delete the transferrecord it state again changes to CANCELED. I would have expected that FAILED was an end-state of the state machine.
It would be very good to have a state transition diagram, at least from the point of view of the SDK-user to see what actions are allowed in what state.

**Comment by fosterzhang** [comment]
That's because TransferUtility.delete(int) always calls cancel before actually removing it from database. From what you described, it looks like you tries to delete a transfer in onError. At this moment, the transfer (Future) is probably not done yet. When delete is called, it cancels the ending transfer and changes its state to CANCELED. Probably we can add some smart logic not to cancel any transfer in a final state: PAUSED, CANCELED, FAILED, COMPLETE.

**Comment by erikvdvelden** [comment]
I do not agree that PAUSED is a final state. You should be able to CANCEL a PAUSED transfer. It would just mean that you change the state to CANCELED, so you would not be able to RESUME.

**Comment by fosterzhang** [comment]
This is improved in v2.2.13 release. Please update the SDK at https://aws.amazon.com/mobile/sdk/. Check out what is changed in the [change log](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md).
