### ISSUE TITLE
How to catch the submission failure of DynamoDBMapper?

### ISSUE THREAD

**Issue by dsuyang** [aws/aws-sdk-android#107]
I might be ignorant of its existence in Android SDK as the iOS SDK can catch the error of internet disconnection using 
```
 [[dynamoDBObjectMapper save:tableRow]
     continueWithExecutor:[AWSExecutor mainThreadExecutor] withBlock:^id(AWSTask *task) {
        if (task.error) {...}});
```
It allows me to see if the row has been submitted successfully or not. 

However, in the Android SDK version, the** try/catch** schema doesn't see to trigger exception when the Internet is disconnected. 

Is this a feature missed in Android SDK or there is a way to catch it? In general, I want to be able to tell if a row has been successfully submitted to the DynamoDB or not. 

Thanks!

**Comment by fosterzhang** [comment]
`DynamoDBObjectMapper` should throw `AmazonClientException` on most operations when network is unavailable. `batchSave` and `batchWrite` don't throw exceptions, but you can find out the exception from their return values `FailedBatch`.

**Comment by dsuyang** [comment]
Thank you! It does help! I noticed AmazonClientException wasn't listed in the SDK sample **userpreferencesom** (only **AmazonServiceException** was shown). That's part of the reason I failed to catch it. Maybe it is worthwhile to catch that in the sample as well? In fact, right now if you run the sample without Internet, it will crash.

**Comment by fosterzhang** [comment]
`AmazonServiceException` is a subclass of `AmazonClientException`. The former are usually errors returned by a service, e.g. [`LimitExceededException`](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/LimitExceededException.html) and [`ProvisionedThroughputExceededException`](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ProvisionedThroughputExceededException.html). The latter includes other errors, like network error, IO error, etc. Both are unchecked exceptions for legacy reason. That's why you don't see try catch around API calls.

**Comment by dsuyang** [comment]
Thank you very much for the clarification!
