### ISSUE TITLE
Forgotten password when email_verified is false

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#142]
Hi,
I'm using _lamba trigger_ to confirm user without  sent _confirm code_ via email or SMS.

It's works well and my user (form cognito console) has these attributes:
> User Status	Enabled / Confirmed
> MFA Status	Disabled
> Last Modified	May 24, 2016 12:59:17 PM
> Created	May 24, 2016 12:59:17 PM
> email_verified	false
> email	my-mail@mail.com

But I can't use _forgotPassword_, server response is:
> Cannot reset password for the user as there is no registered/verified email or phone_number

It's seems a valid message...

But how can I recover forgotten password? Is there a way that user can change his forgotten password?

Maybe change _email_verified_  to TRUE? And how can do it?

Thank you!

**Comment by chetanme** [comment]
The error you are getting is expected. Since, the forgot password functionality relies on a verified email or phone number, a user who has none cannot recover his/her password.

What this means is that the users who are being auto confirmed using the Pre Sign Up trigger should first authenticate using their current password, update and verify either email of phone number. Only then they will be able to use the forgot password functionality.

The _email_verified_ and _phone_verified_ keys are only updated by the user pool service when the user goes through the verification flow. They cannot be updated by developers or users directly.

Hope this answers your questions.

**Comment by adelpuva** [comment]
For verify email (or phone) I must use this services `getAttributeVerificationCode`?

**Comment by chetanme** [comment]
Correct.

[GetUserAttributeVerificationCode](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUserAttributeVerificationCode.html) will deliver the code to a email or phone number. Use [VerifyUserAttribute](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_VerifyUserAttribute.html) with the code and attribute name which is supposed to be verified.

**Comment by adelpuva** [comment]
Thank you
