### ISSUE TITLE
getTime() on a null object in 2.3.9

### ISSUE THREAD

**Issue by mladenrakonjac** [aws/aws-sdk-android#255]
* What service are you using?
AWS Push notifications
* In what version of SDK are you facing the problem?
2.3.9
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No, this is last one. 
* Is this problem related to specific Android/OS version?
I don't think so.
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I can not reproduce it.
* Please include a stacktrace if applicable.
![screen shot 2017-02-17 at 09 01 58](https://cloud.githubusercontent.com/assets/7437403/23057395/4b7f9ec8-f4f0-11e6-90ec-91707f0fa51e.png)

**Comment by azsolinsky** [comment]
Are you sure you are using version 2.3.9 of the SDK. I am fairly positive you are using an older version.  Your stack trace indicates line numbers from [this version](https://github.com/aws/aws-sdk-android/blob/755b79648490bb7fff47b764b616bece5bb05d64/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCachingCredentialsProvider.java) of `CognitoCachingCredentialsProvider`.  This was a bug fixed in version 2.3.9 of the SDK. Notice that the code line numbers in [the latest version](https://github.com/aws/aws-sdk-android/blob/755b79648490bb7fff47b764b616bece5bb05d64/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCachingCredentialsProvider.java) do not match your stack trace.
Please ensure you have updated to the latest version of the SDK.

**Comment by mladenrakonjac** [comment]
![screen shot 2017-02-20 at 08 35 06](https://cloud.githubusercontent.com/assets/7437403/23115809/906b26de-f747-11e6-91c4-efb6756427b9.png)


Sorry but I am using version 2.3.9

**Comment by azsolinsky** [comment]
Did the stack trace come from devices in the field that might not have been updated to the same version that you are now using in your project? If you reproduced the issue yourself, please include steps you took to produce the issue.

Based on what you are showing from your Gradle file the code that was pulled in should not match your stack trace.

Did you clean and re-build the project? Are you using Android Studio? Can you navigate into the de-compiled Java classes and see if the line numbers from CognitoCachingCredentialsProvider match your stack trace?

**Comment by mladenrakonjac** [comment]
At first, I had this bug https://github.com/aws/aws-sdk-android/issues/247. So, because of that I have updated my app to use AWS SDK version 2.3.9. This stack trace is from the last version app. I can confirm it cause I have the version number in Crashalytics. Also, I can confirm it because I don't have problems with issue 247  anymore. 

As always, when I change the version number of the SDK I have to do sync and re-build. Also, I am using Android Studio.

 In meantime, I have updated my app once again. If this crash happens again, I will provide new stack trace here and reopen this issue.

Thanks
