### ISSUE TITLE
Error importing classes

### ISSUE THREAD

**Issue by sharmashivanu** [aws/aws-sdk-android#47]
I am facing the problem to write the column in AWS table.The API which writes the columns in AWS is not found in the current AWS library.I am using the AWS SDK 2.2.2, I have found the link similar to my problem but there solution not working with me.I have attached the screenshots of the error and the documentation of AWS.
Also, following is the stackoverflow link.

http://stackoverflow.com/questions/21933724/aws-dynamodb-tutorial-does-not-import-certain-classes
![screenshot 2015-06-22 18 55 51](https://cloud.githubusercontent.com/assets/5424990/8285020/42539d86-191e-11e5-9e1b-df8c43e69013.png)

**Comment by fosterzhang** [comment]
DynamoDB Document API was added to AWS SDK for Java 2010/10, but it hasn't been migrated to AWS SDK for Android. There are minor differences between these two SDKs. Please checkout the latest [Javadoc](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/) and find out what's available. Here is a [getting started guide](http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/dynamodb_om.html).

**Comment by sharmashivanu** [comment]
hi,

Thanks for your reply.In the documentation, it is mentioned that I have to use Mapping class with predefined attributes.My requirement is to add new attributes to the existing table, but I am confused how to add new user defined attributes to the table.Is there any example/Sample for Android.

**Comment by fosterzhang** [comment]
Please take a look at these blog posts
* [Amazon DynamoDB on Mobile - Part 1: Loading Data](https://mobile.awsblog.com/post/Tx1U4RV2QI1MVWS/Amazon-DynamoDB-on-Mobile-Part-1-Loading-Data)
* [Amazon DynamoDB on Mobile - Part 2: Advanced Data Loading Options](http://mobile.awsblog.com/post/Tx306H0Z3TZ3NDW/Amazon-DynamoDB-on-Mobile-Part-2-Advanced-Data-Loading-Options)
* [Amazon DynamoDB on Mobile - Part 3: Writing Data](http://mobile.awsblog.com/post/Tx1GPB1A28MHQO6/Amazon-DynamoDB-on-Mobile-Part-3-Writing-Data)
* [Amazon DynamoDB on Mobile - Part 4: Local Secondary Indexes](http://mobile.awsblog.com/post/TxTCW7KW8BGZAF/Amazon-DynamoDB-on-Mobile-Part-4-Local-Secondary-Indexes)

PS: please ignore the warning about version 2 SDK. They should work with latest version of AWS Android SDK.

**Comment by sharmashivanu** [comment]
hi,

I have seen these tutorials, but My requirement is to add new columns/attributes of the existing table from the android application.I have attached the screenshot of my dynamoDb, I have marked the black circles around the columns name.
![userdefined columns](https://cloud.githubusercontent.com/assets/5424990/8347889/bb710980-1b29-11e5-8f10-e8464048f34a.png)

**Comment by fosterzhang** [comment]
DynamoDB is a scheme-less NoSQL database. You don't define a column in DynamoDB. Each item (or record) can have arbitrary number of attributes. However items don't necessarily share the same set of attributes other than defined hash key and range key. In the console, attributes are shown in columns, which makes you think DynamoDB has columns.

The following code is taken from the above blogs. It adds an item with 3 attributes "UserId", "RecordId", and "Data". You can add other attributes similarly.
``` java
// Each attribute will be an AttributeValue
Map<String,AttributeValue> item = new HashMap<String, AttributeValue>();
item.put("UserId", 
         new AttributeValue().withN("1234"));
item.put("RecordId", 
         new AttributeValue().withS("FavoriteColors"));
         
// Now that we've added our required key attributes,
// we can add anything else we choose, even a set of strings
item.put("Data",
         new AttributeValue().withSS("Green", "Red", "Black"));
         
// Construct our request, supply table name
PutItemRequest putItemRequest = new PutItemRequest("UserTableExample", item);
```

**Comment by sharmashivanu** [comment]
As you have seen the screen shot of the table, can you please tell me how can I read the data from this table as I have to use the mapping class like this 

@DynamoDBIndexRangeKey(attributeName = "Title") 
public String getTitle() { 
return title; 
} 
public void setTitle(String title) { 
this.title = title;
}


And the Mapping class does not take the variables.

Note: Attributes names are userdefined.

**Comment by fosterzhang** [comment]
There are a couple of questions in this issue. I will answer them all here:

1. Missing import `com.amazonaws.services.dynamodbv2.document.Table` is because document API is not available in AWS SDK for Android. To interact with DynamoDB in Android, you can either use [DynamoDBMapper](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/mobileconnectors/dynamodbv2/dynamodbmapper/DynamoDBMapper.html) or DynamoDB's service APIs like putItem, deleteItem etc.
2. About adding columns, I think there is a misunderstanding of DynamoDB. When you create a DynamoDB table, you define hash key, range key, and indices, but you don't define what attributes (or columns) each item may have. When you create/update an item after a table is created, you can add dynamically add any attributes you want. So what you said about adding `Username` is correct. Well, this is outside the topic of SDK. Please refer to [DynamoDB's developer guide](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html). If you have further questions about the service, please contact customer support of the service.
3. Speaking DynamoDB mapper, it's a library that can help you map DynamoDB attributes to POJO. It's similar to Jackson mapper which maps JSON to POJO. With it, you don't have to do the tedious work to parse attributes and map them to a Java object, or vice versa. Basically, you can define how each item should look like in Java and then define the mapping via annotations, like `@DynamoDBHashKey`, `@DynamoDBRangeKey`, `@DynamoDBAttribute`, etc. For usage about DynamoDB mapper, please take a look at [AWS Mobile SDK for Android Developer Guide](http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/dynamodb_om.html).

Other helper resources are:
* [DynamoDB UserPreference ObjectMapper Sample](https://github.com/awslabs/aws-sdk-android-samples/tree/master/DynamoDBMapper_UserPreference_Cognito)
* [Amazon DynamoDB on Mobile - Part 1: Loading Data](https://mobile.awsblog.com/post/Tx1U4RV2QI1MVWS/Amazon-DynamoDB-on-Mobile-Part-1-Loading-Data)
* [Amazon DynamoDB on Mobile - Part 2: Advanced Data Loading Options](http://mobile.awsblog.com/post/Tx306H0Z3TZ3NDW/Amazon-DynamoDB-on-Mobile-Part-2-Advanced-Data-Loading-Options)
* [Amazon DynamoDB on Mobile - Part 3: Writing Data](http://mobile.awsblog.com/post/Tx1GPB1A28MHQO6/Amazon-DynamoDB-on-Mobile-Part-3-Writing-Data)
* [Amazon DynamoDB on Mobile - Part 4: Local Secondary Indexes](http://mobile.awsblog.com/post/TxTCW7KW8BGZAF/Amazon-DynamoDB-on-Mobile-Part-4-Local-Secondary-Indexes)

**Comment by wdane** [comment]
Assuming fosterzhang's answer resolved the questions.  Closing for now.
