### ISSUE TITLE
State of S3 TransferObserver remains WAITING and TransferListener doesn't call

### ISSUE THREAD

**Issue by usmanrana07** [aws/aws-sdk-android#513]
Hi! I'm using andrpod-sdk-s3 for Files transfer to S3, but the issue that i'm facing is that after calling 'upload' the state of observer remains as 'WAITING' and never changes and i don't get any callback in TransferListener. The version of sdk is '2.6.27' and android version is 7.0 . What is causing this issue?

**Comment by kvasukib** [comment]
@usmanrana07 Have you declared the TransferService in AndroidManifest.xml?

```xml
<application ... >

   <!- Other manifest / application items . . . ->

   <service android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService" android:enabled="true" />

</application>
```

**Comment by usmanrana07** [comment]
yes i've declared that, The thing is that observer Listener doesn't work when i get list of TransferObservers and set listener to them when application is closed and reopened again. While listener works fine if i set it to TransferObserver in same method where i start upload.

**Comment by kvasukib** [comment]
@usmanrana07 I understand your concern better now. We have an issue related to synchronization when querying the database for transfer records when an upload is being queued. At this moment, I would recommend attaching the TransferListener object in the TransferObserver returned by the upload/download method call. Alternatively, you can query the TransferObserver for the state and progress by calling the .refresh() method on the object. I will update this thread when the root cause of the synchronization issue has been identified.

**Comment by usmanrana07** [comment]
even observer.refresh() didn't work and neither the listener.

**Comment by usmanrana07** [comment]
as refresh doesn't resume the request, so if i use` 'getTransferUtility(context).resume(observer.getId());' `  it starts the request again instead of resuming from the point where connection was broken.

**Comment by kvasukib** [comment]
@usmanrana07 This issue is only present in the AWS Android SDK and not in AWS iOS SDK.

Also, can you try the following:

**Workaround-1:**

```xml
<service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:process=":sync"/>
```

**Workaround-2:**

```xml
<service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:process=":main"/>
```

Can you try the above two workarounds and see the behavior?
