### ISSUE TITLE
AWS Android SDK distributed from aws.amazon.com has wrong classes

### ISSUE THREAD

**Issue by Miksu82** [aws/aws-sdk-android#58]
It looks like the 2.2.6 package  that can be downloaded here http://sdk-for-android.amazonwebservices.com/latest/aws-android-sdk.zip has some strange imports.

At least decompiling aws-android-sdk-s3-2.2.6.jar shows 

```java
import com.amazonaws.org.apache.commons.logging.Log;
import com.amazonaws.org.apache.commons.logging.LogFactory;
```

So when I try to instantiate **AmazonS3Client** I get 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/org/apache/commons/logging/LogFactory;
```

In the jar downloaded from the maven repo http://central.maven.org/maven2/com/amazonaws/aws-android-sdk-s3/2.2.6/aws-android-sdk-s3-2.2.6.jar

the imports are correct 

```java
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
```

**Comment by fosterzhang** [comment]
The archives distributed on the website and through Maven are packaged slightly different, by design. For the website distribution, we use Jarjar to bundle two dependencies Apache Commons Logging 1.1.1 and Google's Gson 2.2.4 into the core runtime library under com.amazonaws namespace. The idea is to take care of dependencies for our developers who can simply drop the libraries into the IDE without worrying about additional dependencies or potential dependency conflicts. However, for the Maven distribution, dependencies are handled by Maven, so there is no need to bundle them.

Both archives are tested. You should be able to use either one, but please don't mix them together, or else you may see ClassNotFoundException.

**Comment by Miksu82** [comment]
Thanks for the explanation. I'll close this issue.
