### ISSUE TITLE
hostname was not verified error.

### ISSUE THREAD

**Issue by matijagorsek** [aws/aws-sdk-android#60]
Please can someone help with this error? Upload worked till update of sdk on Saturday. 

StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append(Util.getRandomString(15))
                .append(".mp4");
        String videoName = stringBuilder.toString();
        File video = new File(filePathVideo);

        CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                mContext.getApplicationContext(),
                "", // Identity Pool ID,deleted i have this one.
                 // Region,also like a identity pool id.
        );

        AmazonS3Client s3Client = new AmazonS3Client(credentialsProvider);
        PutObjectRequest videoRequest = new PutObjectRequest(Constants.BUCKET_VIDEOS, videoName, video);

        PutObjectResult videoResponse = s3Client.putObject(videoRequest);

        if (videoResponse != null)
            return videoName;
        else
            return null;

Here is the error: Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Hostname 'movv.user-videos.s3.amazonaws.com' was not verified.

**Comment by shklnrj** [comment]
I had the same problem. 
There seems the be a bug in the latest version of the SDK where if you have a dot(.) in the bucket name, there is some problem. This issue needs to be fixed. Meanwhile if your code can take care of bucket name, please change the bucket name to something like-
movv-user-videos from the current movv.user-videos.

For me this worked as my codebase takes care of bucketname change. I am sure this would fixed soon because this seems a BIG bug to me.

**Comment by shklnrj** [comment]
Ah seems like the previous issue was the same one.
https://github.com/aws/aws-sdk-android/issues/59

**Comment by matijagorsek** [comment]
i know just wanted to check. thx a lot.

**Comment by hyankelwin** [comment]
@shklnrj Dude, it helped, thanks a lot.
