### ISSUE TITLE
TransferObserver/TransferListener - Listen for results outside of main thread?

### ISSUE THREAD

**Issue by erawhctim** [aws/aws-sdk-android#85]
Is there a way to do this? I'm utilizing an async "task" framework and downloading files in a background thread, but TransferObserver sends its updates to the TransferListener on the main thread, causing an ANR.

Is there a way TransferObserver can be modified with an additional parameter or constructor to allow this behavior?

**Comment by fosterzhang** [comment]
Unfortunately, there is no flag to invoke callbacks off the main thread. The callbacks are triggered in various places, some from worker threads, some from the service, and some from the caller's thread. To standardize it, we enforce all callbacks run on the main thread. If you have a long running task in the callback, please move it to a background thread.

**Comment by zhoul-HS** [comment]
Does this mean it's impossible to use the TransferObserver in a background service on a different process?

**Comment by fosterzhang** [comment]
@zhoul-HS you can still use it off the main thread. Just be careful what to do in the callbacks. Since the callbacks are called on the main thread, you can manipulate UI without `Activity.runOnUiThread(Runnable)` or `Handler.post(Runnable)`. The trade off is that if you want to do a long running task, you need to spawn off a thread to run it.

``` java
new TransferListener() {
    @Override
    public void onStateChanged(int id, TransferState state) {
        if (TransferState.Complete.equals(state)) {
            // update ui
            progressDialog.dismiss();
            // make a network call. must run on a thread
            // you can also use AsyncTask
            new Thread(new Runnable() {
                @Override
                public void run() {
                    ...
                }
            }).start();
        }
    }
}
```

**Comment by zhoul-HS** [comment]
The problem i'm facing at the moment, is that I start and initialize the TransferUtility from a background service **in another process**. But the service itself starts **inside my app process**, and so when `onStartCommand` is called, my s3 client is null:
```java
    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {

        this.startId = startId;
        String keyForS3Client = intent.getStringExtra(TransferUtility.KEY_FOR_S3_WEAK_REFERENCE);
        s3 = S3ClientWeakReference.get(keyForS3Client);
        if (s3 == null) { // TRUE !!!
            Log.w(TAG, "TransferService can't get s3 client, it will stop.");
            stopSelf();
        }

        enqueueUpdate();
        /*
         * The service will not restart if it's killed by system.
         */
        return START_NOT_STICKY;
    }
```
that's because S3ClientWeakReference is empty since it is static and not shared between the processes, and thus I cannot use the TransferUtility!

This is a major issue, but it can probably be resolved if I initialize the transferutility in my app process.
Lets imagine we resolve this. Now everything is split - my progress is on the main thread of the background service, but the TransferService is on my app process.

Something is wrong with the design here, or with the Android SDK - why does the TransferService start on the application process and not the service process?

**Comment by fosterzhang** [comment]
@zhoul-HS This is a very interesting discussion. However it's off the topic. Would you please create a new issue? Let's continue the discussion there. Thank you.

**Comment by fosterzhang** [comment]
Closing this as the original question is answered. Feel free to reopen it if necessary.
